<?php

use PHPUnit\Framework\TestCase;

/**
 *  Corresponding Class to test YourClass class
 *
 *  For each class in your library, there should be a corresponding Unit-Test for it
 *  Unit-Tests should be as much as possible independent from other test going on.
 *
 *  @author yourname
 */
class IFCStepFileHeaderTest extends TestCase
{

    /**
     * Just check if the YourClass has no syntax error
     *
     * This is just a simple check to make sure your library has no syntax error. This helps you troubleshoot
     * any typo before you even use this library in a real project.
     *
     */
    public function testIsThereAnySyntaxError()
    {
        $var = new Serversidebim\IFCReader\IFCStepFileHeader;
        $this->assertTrue(is_object($var));
        unset($var);
    }

    public function testParseHeader()
    {
        $headerstring = "HEADER;

/******************************************************************************************
* STEP Physical File produced by: The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013
* Module:                         EDMstepFileFactory/EDMstandAlone
* Creation date:                  Fri May 05 15:27:06 2017
* Host:                           L603014
* Database:                       D:\Users\veem5\AppData\Local\Temp\{DCA5F9F4-6A29-4EB8-AA26-75F6D95D14E8}\ifc
* Database version:               5507
* Database creation date:         Fri May 05 15:27:04 2017
* Schema:                         IFC2X3
* Model:                          DataRepository.ifc
* Model creation date:            Fri May 05 15:27:04 2017
* Header model:                   DataRepository.ifc_HeaderModel
* Header model creation date:     Fri May 05 15:27:04 2017
* EDMuser:                        sdai-user
* EDMgroup:                       sdai-group
* License ID and type:            5605 : Permanent license. Expiry date:
* EDMstepFileFactory options:     020000
******************************************************************************************/
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2017-05-05T15:27:06',(''),(''),'The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013','20150220_1215(x64) - Exporter 16.0.428.0 - Default UI','');
FILE_SCHEMA(('IFC2X3'));
ENDSEC;";

        $header = new Serversidebim\IFCReader\IFCStepFileHeader();
        $header->parseRaw($headerstring);

        $this->assertEquals(['IFC2X3'], $header->FILE_SCHEMA->schema);

        $this->assertEquals($header->SECTION_CONTEXT->context, null);
    }

    public function testParseHeaderNoNewLine()
    {
        $headerstring = "HEADER;FILE_DESCRIPTION(('ViewDefinition [CoordinationView_V2.0, QuantityTakeOffAddOnView]','Option [Drawing Scale: 100.000000]','Option [Global Unique Identifiers (GUID): Keep existing]','Option [Elements to export: Entire project]','Option [Partial Structure Display: Entire Model]','Option [IFC Domain: All]','Option [Structural Function: All Elements]','Option [Convert Grid elements: On]','Option [Convert IFC Annotations and ARCHICAD 2D elements: Off]','Option [Convert 2D symbols of Doors and Windows: Off]','Option [Explode Composite and Complex Profile elements into parts: Off]','Option [Export geometries that Participates in Collision Detection only: Off]','Option [Multi-skin complex geometries: Building element parts]','Option [Elements in Solid Element Operations: Extruded/revolved]','Option [Elements with junctions: Extruded/revolved without junctions]','Option [Slabs with slanted edge(s): Extruded]','Option [Use legacy geometric methods as in Coordination View 1.0: Off]','Option [IFC Site Geometry: As boundary representation (BRep)]','Option [IFC Site Location: At Project Origin]','Option [Curtain Wall export mode: Container Element]','Option [Railing export mode: Single Element]','Option [Stair export mode: Container Element]','Option [Properties To Export: Current Scheme properties only]','Option [Space containment: Off]','Option [Bounding Box: Off]','Option [Geometry to type objects: Off]','Option [Element Properties: All]','Option [Building Material Properties: Off]','Option [Element Parameters: Off]','Option [Component Parameters: Off]','Option [IFC Base Quantities: On]','Option [Door Window Parameters: Off]','Option [IFC Space boundaries: Off]','Option [ARCHICAD Zone Categories as IFC Space classification data: Off]','Option [Element Classifications: On]'),'2;1');
FILE_NAME('D:\\Users\\CHEI.WBAD\\Desktop\\ARCHICAD 22 Research and Findings\\Test ARCHICAD\\To test commit system in IBIS\\STS Property Set to Wall #1.ifc','2019-10-04T11:44:05',('Architect'),('Building Designer Office'),'The EXPRESS Data Manager Version 5.02.0100.09 : 26 Sep 2013','IFC file generated by GRAPHISOFT ARCHICAD-64 22.0.0 INT FULL Windows version (IFC add-on version: 6021 INT FULL).','The authorising person');
FILE_SCHEMA(('IFC2X3'));
ENDSEC;";

        $header = new Serversidebim\IFCReader\IFCStepFileHeader();
        $header->parseRaw($headerstring);

        $this->assertEquals("ViewDefinition [CoordinationView_V2.0, QuantityTakeOffAddOnView]", $header->FILE_DESCRIPTION->description[0]);

        $this->assertEquals(['IFC2X3'], $header->FILE_SCHEMA->schema);

        $this->assertEquals($header->SECTION_CONTEXT->context, null);
    }
}
